### ISSUE TITLE
It seems doesn't work

### ISSUE THREAD

**Issue by aolphn** [x0r19x91/010-Editor-k3yg3n#2]
![image](https://user-images.githubusercontent.com/9359883/49485828-40fe3b80-f877-11e8-9377-89ff4ea7a7a6.png)

**Comment by x0r19x91** [comment]
Try clearing the registry entries for 010 Editor using the `Clear Registry` button

**Comment by aolphn** [comment]
Thanks so much ,it work fine after Clear Registry
