### ISSUE TITLE
Hotfixes

### ISSUE THREAD

**Issue by VisualStudio-zz** [x0r19x91/010-Editor-k3yg3n#3]
I think they might've pushed a hotfix if that's possible, the keygen doesn't appear to work anymore.

**Comment by x0r19x91** [comment]
Try using `Clear Registry` button

**Comment by VisualStudio-zz** [comment]
I've already tried to do that, it still gives me the same error.

**Comment by x0r19x91** [comment]
Can you give a screenshot?

**Comment by VisualStudio-zz** [comment]
![screenshot](https://ishr.ink/6DOG3deL)

**Comment by x0r19x91** [comment]
Click on `Clear Registry` and restart `010 Editor`

**Comment by VisualStudio-zz** [comment]
I did, it does nothing.

**Comment by VisualStudio-zz** [comment]
Ok so the reason was because I was using the portable application and it doesn't use the registry.

**Comment by x0r19x91** [comment]
Thanks for Highlighting. I'll check out the portable version
